version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install yarn
      - yarn
  build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
